{% set name = "PEKA" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/ulelab/peka/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: cddbe86774de3de6a7c4ed06b7187d812d736fdc30e19f384170c6bdd77b1174

build:
  number: 0
  entry_points:
    - peka = peka:main
  script: "{{ PYTHON }} -m pip install . -vvv --no-build-isolation --no-deps"
  noarch: python
  run_exports:
    - {{ pin_subpackage('peka', max_pin="x") }}

requirements:
  host:
    - pip
    - python ==3.7
  run:
    - python ==3.7
    - matplotlib-base ==3.1.2
    - numpy ==1.17.4
    - pybedtools ==0.8.0
    - scipy ==1.6.2
    - seaborn ==0.9.0
    - plumbum ==1.6.8
    - scikit-learn ==0.21.3
    - pandas ==0.24.2
    - textdistance ==4.1.3

test:
  commands:
    - peka --help

about:
  home: "https://github.com/ulelab/peka"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "Analysis of kmers located around locations of interest"

extra:
  recipe-maintainers:
    - marc-jones
    - codeprimate123
    - kkuret
